### PR TITLE
Added `isValid` and `calculateChecksum`

### PR DESCRIPTION
**Pull request by evanwporter**

### CODE REVIEW

**Review by andrewbenington — APPROVED** [review]

**Comment by andrewbenington** [comment]
Does it let you merge approved pull requests? I don't want to take credit for your code by merging it myself lol

**Comment by andrewbenington** [comment]
@evanwporter

**Comment by evanwporter** [comment]
Yeah looks like it. But I think it still gives me credit.

**Comment by andrewbenington** [comment]
Yeah it gives credit to whomever merges the pull request because its a squash commit (all of the branch commits are "squashed" into a single commit attributed to the person merging the PR)

**Pull request merged**
